name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        run: docker build -t multicloud-app:latest .
      - name: Run Trivy scan
        run: bash ./security/trivy-scan.sh multicloud-app:latest || true
